---
title: "workshop09"
author: "Jayne Campbell"
format: html
editor: visual
---

## load libraries

load libraries

```{r}
library(tidyverse)
library(lterdatasampler)
library(ggeffects)
library(here)
```

I am reading in data here (edit later)

```{r}
data(pie_crab)
```

I will visualize the data!!!

```{r}
ggplot(aes(x=latitude, y=size), data=pie_crab) + # create the plot
  geom_point(color = "orange") + # scatterplot, the points are orange
  labs(x = "Latitude", y = "Size") + # update axes labels
  theme_minimal() # update the theme to not have grid (aka crissycrossies)
```

```{r}
crab_model <- lm(size ~ latitude, 
                 data = pie_crab)

par(mfrow = c(2, 2))
plot(crab_model)
```

Run the model and interpret

```{r}
summary(crab_model) # look at model output
```

Summarize our results:

slope: 0.49

y-intercept: -3.6 +/- 1.27

For every 1 degree increase in latitude, we expect to see a 0.49 increase in crab size +/- 0.034 mm.

Model statistics: F(1,390) = 208.5, p < 0.001, alpha = 0.05, R^2^ = 0.35